logging:
  file:
    path: ${user.home}
  path: ${logging.file.path}
spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations[0]: classpath:/static/
    static-locations[1]: classpath:/static/assets/
    static-locations[2]: classpath:/static/packages/
  main:
    lazy-initialization: false
  application:
    name: hotswap
    id: 7d450480-f44e-4e2c-8a7f-956e2905229d
  liquibase:
    enabled: false
  initDatabase:
    enabled: false
  quartz:
    enabled: true
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://59.111.105.41:3306/defaulttenant-dev-hotswap-OLNsqo?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: defau_Jto0c_user
    password: ''
    connection-timeout: 3000
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  messages:
    basename: i18n/messages
  profiles:
    include: auth
mybatis:
  mapper-locations: classpath:mappings/**/*Mapper.xml
  type-handlers-package: com.defaulttenant.hotswap.repository.handler
  configuration:
    database-id: mysql
    default-enum-type-handler: com.defaulttenant.hotswap.repository.handler.AutoEnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
lcp:
  snowflakeNodeId: null
  authCenter:
    enable: true
    address: http://10.194.73.105/gateway/nuims/nuims
    host: 10.194.73.105
    security:
      lockMilliseconds: 900000
      maxFailureTimes: 5
  flowUrl: http://api.gateway.lowcode/gateway/bpms
  gatewayUrl: ''
  audit:
    enable: true
    address: http://platform-audit.lcp.service.163.org
  uiResourceAddress: /client.js
  gatewayType: light
  upload:
    sinkType: s3
    sinkPath: /app
    s3Address: http://minio-api.codewave-dev.163yun.com
    s3AccessKey: ''
    s3SecretKey: ''
    s3Bucket: lowcode-static
    access: public
    ttl: -1.0
    cdnAddress: ''
  logResponse: false
  logRequest: true
  quartzTables:
    SIMPROP_TRIGGERS: N7D45048_SIMPROP_TRIGGERS
    BLOB_TRIGGERS: N7D45048_BLOB_TRIGGERS
    TRIGGERS: N7D45048_TRIGGERS
    SIMPLE_TRIGGERS: N7D45048_SIMPLE_TRIGGERS
    LOCKS: N7D45048_LOCKS
    CRON_TRIGGERS: N7D45048_CRON_TRIGGERS
    FIRED_TRIGGERS: N7D45048_FIRED_TRIGGERS
    CALENDARS: N7D45048_CALENDARS
    JOB_DETAILS: N7D45048_JOB_DETAILS
    SCHEDULER_STATE: N7D45048_SCHEDULER_STATE
    PAUSED_TRIGGER_GRPS: N7D45048_PAUSED_TRIGGER_GRPS
  report:
    host: ''
    tokenKey: ''
    domainId: null
    projectId: null
    reportIdMap: {}
    componentIdMap: {}
  nuims: http://nuims.low-code:8081
  private: null
  frontends:
    pc:
      name: pc
      path: /
      title: PC端
      type: pc
upload:
  base-path: app
file:
  types: text/plain;text/html;text/css;application/javascript
logicAuthFlag: false
auth:
  pass:
    salt: $2a!@#$%^&*()_+
  token:
    secret: 1227be45c5d97af
    expire: 86400
  plugin:
    list:
      Normal:
        category: main
  types: Normal
  Normal: '{"category":"main"}'
gw:
  app:
    addr:
      lowcode: http://lcap.low-code:22988
      nuims: http://nuims.low-code:8081
custom:
  api:
    context-path: /
  system:
    time-zone: user
