server:
  port: 8081


hazelcast:
  network:
    port: 5701
  cluster:
    members: 127.0.0.1:5701,127.0.0.1:5702


spring:
  servlet:
    multipart:
      max-file-size: 10MB


  application:
    name: mall-tiny
  profiles:
    active: dev
#  main:
#    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

logging:
  config: classpath:log4j2.xml

secure:
  ignored:
    urls: #安全路径白名单
      - /
      - /V1/**
      - /admin/**
      - /swagger-ui.html
      - /swagger-ui/
      - /*.html
      - /favicon.ico
      - /**/*.html
      - /**/*.css
      - /**/*.js
      - /swagger-resources/**
      - /v3/api-docs/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /menu/treeList
      - /system/**
      - /resource/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
