server:
  port: ${PORT:8089}
  servlet.context-path: ${CONTEXTPATH:/shardingJdbc-service}
logging:
  file: ${LOGGING_FILE:sharding-jdbc.log}

spring:
  profiles: prd
  jpa:
    show-sql: true
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        username: finance
        password: zzzZZZ000
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://rm-8vb2zrtvy2235lo75eo.mysql.zhangbei.rds.aliyuncs.com/finance?useUnicode=true&characterEncoding=utf-8&useSSL=false
        hikari:
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1800000
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        username: finance
        password: zzzZZZ000
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://rm-8vb2zrtvy2235lo75eo.mysql.zhangbei.rds.aliyuncs.com/sharding-jdbc?useUnicode=true&characterEncoding=utf-8&useSSL=false
        hikari:
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1800000

    sharding:
      tables:
        etl_order:
          actualDataNodes: ds0.etl_order$->{0..4},ds1.etl_order$->{5..9}
          databaseStrategy:
            standard:
              shardingColumn: order_id
              preciseAlgorithmClassName: com.lvmm.shardingjdbc.shardingJdbc.StandDBShardingAlgorithm
              rangeAlgorithmClassName: com.lvmm.shardingjdbc.shardingJdbc.StandDBShardingAlgorithm
          tableStrategy:
            standard:
              shardingColumn: order_id
              preciseAlgorithmClassName: com.lvmm.shardingjdbc.shardingJdbc.StandTableShardingAlgorithm
              rangeAlgorithmClassName: com.lvmm.shardingjdbc.shardingJdbc.StandTableShardingAlgorithm
        etl_order_item:
          actualDataNodes: ds0.etl_order_item$->{0..4},ds1.etl_order_item$->{5..9}
          databaseStrategy:
            standard:
              shardingColumn: order_id
              preciseAlgorithmClassName: com.lvmm.shardingjdbc.shardingJdbc.StandDBShardingAlgorithm
              rangeAlgorithmClassName: com.lvmm.shardingjdbc.shardingJdbc.StandDBShardingAlgorithm
          tableStrategy:
            standard:
              shardingColumn: order_id
              preciseAlgorithmClassName: com.lvmm.shardingjdbc.shardingJdbc.StandTableShardingAlgorithm
              rangeAlgorithmClassName: com.lvmm.shardingjdbc.shardingJdbc.StandTableShardingAlgorithm
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 39.101.201.47:9300
      repositories:
        enabl: true
