server:
  port: ${PORT:8080}
  servlet.context-path: ${CONTEXTPATH:/shardingJdbc-service}
logging:
    file: E:\home\aaa\ggg\dddd\ddd\shardingJdbc-service.log

spring:
  jpa:
    show-sql: true
  datasource:
    username: finance
    password: zzzZZZ000
    DriverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-8vb2zrtvy2235lo75eoz.mysql.zhangbei.rds.aliyuncs.com/finance?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
